### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by MliarD** [baaivision/tokenize-anything#7]
Thanks for your contribution, I ran into some problems with the Inference Guide, I have the same output as In [5] : (1024, 964, 3) <- (1264, 1190) * (0.810126582278481, 0.810126582278481), but I met some problems In [7]. 
The error is reported as follows:
Traceback (most recent call last):
  File "f:\tokenize\notebooks\tap.py", line 65, in <module>
    outputs = model.get_outputs(inputs)
  File "D:\anaconda3\envs\tokenize\lib\site-packages\tokenize_anything\modeling\image_tokenizer.py", line 103, in get_outputs
    return self.image_decoder(inputs)
  File "D:\anaconda3\envs\tokenize\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\envs\tokenize\lib\site-packages\tokenize_anything\modeling\image_decoder.py", line 219, in forward
    outputs = self.get_outputs(inputs)
  File "D:\anaconda3\envs\tokenize\lib\site-packages\tokenize_anything\modeling\image_decoder.py", line 199, in get_outputs
    query, key = self.transformer(query, key, query, inputs["img_pos"])
  File "D:\anaconda3\envs\tokenize\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\envs\tokenize\lib\site-packages\tokenize_anything\modeling\image_decoder.py", line 138, in forward
    query, key = blk(query, key, query_pos, key_pos)
  File "D:\anaconda3\envs\tokenize\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\envs\tokenize\lib\site-packages\tokenize_anything\modeling\image_decoder.py", line 96, in forward
    query = self.norm1(self.self_attn(query, query, query))
  File "D:\anaconda3\envs\tokenize\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\envs\tokenize\lib\site-packages\tokenize_anything\modeling\image_decoder.py", line 66, in forward
    o = flash_attn_func(q, k, v, softmax_scale=self.scale)
TypeError: 'NoneType' object is not callable

My environment is as follows:
opencv-python=4.9.0.80
Pillow=10.0.1
gradio-image-prompter=3.23.0
sentencepiece=0.1.99
torch=1.13+cu116
flash-attn=2.4.2
python=3.8.18

**Comment by PhyscalX** [comment]
Hi, @MliarD 

Please refer [Issue2](https://github.com/baaivision/tokenize-anything/issues/2) to resolve your Jupyter problem.

BTW, FlashAttention2 is not officially supported for Windows, do you run TAP on Windows?

**Comment by MliarD** [comment]
> Hi, @MliarD
> 
> Please refer [Issue2](javascript:void(0);) to resolve your Jupyter problem.
> 
> BTW, FlashAttention2 is not officially supported for Windows, do you run TAP on Windows?

Ok, I usually run on ubuntu, but this error report is really windows. Running on ubuntu, the error type is the same, thank you for reminding me that it does not support windows, I will try again.
